### ISSUE TITLE
Custom card components in Engineering Section

### ISSUE THREAD

**Issue by adamlodge** [fargeo/sfport-pkg#4]
- Finalize the auto-calculations for nodes
- Dial in the workflow for entry of nodes that are dependent on downstream cards... by pass the requirement to enter a value for auto-calculated stuff necessary to get to the downstream stuff that has the data upon which the calculation is made.
- Make sure card components render in the report properly

**Comment by adamlodge** [comment]
#11

**Comment by adamlodge** [comment]
I notice that Ryan's number formatting is not applying to the nodes managed with this card component.  

![Screen Shot 2019-03-13 at 11.19.37 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/9ad494bf-c661-4b7d-82fb-99d8b72b0878)

**Comment by chiatt** [comment]
@adamlodge To QA, you'll need the latest from arches.

**Comment by adamlodge** [comment]
Yep
