### ISSUE TITLE
Finalize Branding for the Splash Page

### ISSUE THREAD

**Issue by adamlodge** [fargeo/sfport-pkg#46]
- port logo
- verbiage on 3-image carousel
- "Arches - Data management and integration platform"

**Comment by adamlodge** [comment]
![Picture1.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/48e4d508-51ec-4917-8b13-5793b7492fe2)

Arches
A Data Management and Integration Platform

Project Tracking
Manage and Track the Status of Your Projects

Permits and Mitigations
Manage the Permit Entitlements and Monitor Your Project Mitigations

**Comment by dwuthrich** [comment]
@adamlodge  We should make the first bullet:
Arches
An Information Management and Integration Platform
