### ISSUE TITLE
Remove (or hide) the Related Resources Section of Report

### ISSUE THREAD

**Issue by adamlodge** [fargeo/sfport-pkg#5]
This is a one-resource-model Arches deployment.  The related resources section of the report will just add confusion

**Comment by ryan86** [comment]
On second thought it was determined that a project could potentially relate to another project. INstead of removing the related resources section of the report/forms just relabel "related resources" to "related projects"

**Comment by adamlodge** [comment]
Looks good in the report.  Can we make the same page in the resource editor too?

![Screen Shot 2019-02-19 at 3.47.01 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/0276beab-c22c-4eed-9058-29152fd2ec1f)

**Comment by dwuthrich** [comment]
Can’t projects be related to one another?

**Comment by adamlodge** [comment]
I think we made a decision to not do this because it will entail more effort than it's worth.  I checked the latest and this request is not implemented, so I'll close this for now.
