### ISSUE TITLE
bug: Issue with reporting on Subproject aggregate data

### ISSUE THREAD

**Issue by adamlodge** [fargeo/sfport-pkg#53]
This project has one subproject with applied mitigations, and another subproject with no applied mitigations.  The subproject with no applied mitigations indicates that it does have applied mitigations in the aggregate information in the report.  Solution could be to use the same text as you are using in the card for subprojects with no applied mitigations "Mitigations: No mitigations yet applied to this sub-project"

![Screen Shot 2019-04-04 at 11.04.23 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/f4af9429-6ad5-48ee-a5bf-2bceb140f344)

**Comment by dwuthrich** [comment]
@adamlodge Another approach is to just improve the presentation of subproject information in a that makes it easier to see the relationships between subproject and mitigations.  We could explore a better template for this.

**Comment by adamlodge** [comment]
bueno
