### ISSUE TITLE
Project Initiation Form/Report

### ISSUE THREAD

**Issue by adamlodge** [fargeo/sfport-pkg#6]
Current thinking is to add it as a tab that is accessible from within the default report.  Attached image outlines the fields that should be available in the report.  The use case is that this report will be printed, signed by proper authority, scanned, and uploaded to the DB as a file to formalize project initiation.

[https://app.zenhub.com/files/113388738/93cb7d80-973a-4403-899f-75b5cff3dc58/download](https://app.zenhub.com/files/113388738/93cb7d80-973a-4403-899f-75b5cff3dc58/download)

**Comment by ryan86** [comment]
This ticket has been deprecated in favor of using a data model approach to create an 'approval' node that may only be accessed by the appropriate users with approval privileges.

**Comment by adamlodge** [comment]
Project Initiation portion of the model is updated to support this
