### ISSUE TITLE
In report, show subproject geoms and forge interaction with relevant attributes lower down on report

### ISSUE THREAD

**Issue by adamlodge** [fargeo/sfport-pkg#7]
Open to thinking through how this interaction should present in ux.

**Comment by adamlodge** [comment]
@robgaston Looks really good.  One issue I'm seeing however, is printable report got thrown a bit.
![Screen Shot 2019-04-03 at 9.34.51 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/c3f4cb1d-8579-42be-8d08-6e78b138f24c)

**Comment by robgaston** [comment]
@adamlodge I'm not able to reproduce that print bug you show above - is this possibly a separate issue?

**Comment by adamlodge** [comment]
closing this ticket, as original intent is served.  Opening another for the printing issue.
