### ISSUE TITLE
Updates to Projects Dashboard

### ISSUE THREAD

**Issue by adamlodge** [fargeo/sfport-pkg#8]
Add the following:
- number of mitigations
- number of completed mitigations
- number of mitigations pending
- Duration of pending mitigations

*Make sure dashboard content is constrained by search results (Arches task funded by sfport)

**Comment by adamlodge** [comment]
We will need to get feedback from Port on whether this information should be scraped from "mitigation applied to subproject", or if we need to add additional attributes to mitigations.

**Comment by adamlodge** [comment]
Looks good except that the styles for the values in the cells seem inconsistent.  See screenshot:

![Screen Shot 2019-03-06 at 5.52.50 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/9b7b5c3b-0e23-49f1-98d8-b9633ece250d)

**Comment by adamlodge** [comment]
Looks good for now, but there will likely be changes based on client feedback.  I'm putting this into icebox until we hear back.

**Comment by adamlodge** [comment]
Client says abandon this effort because they want the information rolled up at the subproject level.  Closing this ticket and making another one to build a card component that aggregates the relevant data to the appropriate card.

**Comment by whatisgalen** [comment]
yup, removing these columns:
number of mitigations
number of completed mitigations
number of mitigations pending
Duration of pending mitigations

**Comment by adamlodge** [comment]
meets reqt

**Comment by adamlodge** [comment]
requires code review

**Comment by adamlodge** [comment]
meets functional requirement
